# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e091de8bfdb64ed68bb438876c384770e88672f46c6986f6f714136c419b95018a86b19fa76857560613792aff10f6c2c4f63158ff41852c31818d160239d3

test:
  secret_key_base: 04cb6a70c58f16eb9466731cc6c0e26ab54fe936bd89c456ef48377ed20e8ec5e838652847b2974ecc755930c4aa04d85a4de86b452ceeb6f260bb6aff2ea976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
